declare module "*.svg";
declare module "*.png";
declare module "*.pdf";
declare module "*.jpeg";
declare module "*.jpg";
declare module "@left4code/tw-starter/dist/js/dom";
declare module "@/react-input-mask";
declare module "@/base-components";
declare module "@/utils";
